name: Release from master

on:
  push:
    branches: [ master ]
  
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compute tag name
        id: compute-tag
        run: |
          echo "Computing next tag number"
          LASTPATCH=$(git describe --tags | cut -d- -f1 | cut -d. -f3)
          PATCH=$(($LASTPATCH+1))
          echo "New tag name: 2.1.${PATCH}"
          echo "::set-output name=tagname::2.1.${PATCH}"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      
      - name: Build release assets
        run: bundle exec rake book:build
        
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.compute-tag.outputs.tagname }}
          commit: master
          artifacts: './progit.epub,./progit.mobi,./progit.pdf,./progit.html'
          
      - name: Generate Changelog
        id: release-changelog
        uses: mikepenz/release-changelog-builder-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set changelog to the release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.compute-tag.outputs.tagname }}
          commit: master
          allowUpdates: true
          body: ${{ steps.release-changelog.outputs.changelog }}
